name: Publish to Modrinth
on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip Datapack
        run: zip -r "Fireworks 2.0.zip" . -x ".github/*" ".git/*" "*.yml" "README.md" "assets/*" # Package files into .zip

      - name: Zip Resourcepack
        run: zip -r "Fireworks Translations.zip" . -x ".github/*" ".git/*" "*.yml" "README.md" "data/*" "Fireworks.zip" # Package files into .zip

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: "yFGB1mRk"
          vname: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          files: |-
            "Fireworks 2.0.zip"
            "Fireworks Translations.zip"
          primary-file: "Fireworks 2.0.zip"
          file-types: "Fireworks Translations.zip"=optional-resource-pack
          loaders: "datapack"
          game-versions: |-
            26.2-pre-2
          channel: "alpha"
