name: Publish to Modrinth
on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip Datapack
        run: zip -r Fireworks-DP_v${{ github.event.release.tag_name }}.zip . -x ".github/*" ".git/*" "*.yml" "README.md" "assets/*" # Package data files into .zip

      - name: Zip Resourcepack
        run: zip -r Fireworks-RP_v${{ github.event.release.tag_name }}.zip . -x ".github/*" ".git/*" "*.yml" "README.md" "data/*" "Fireworks-DP_v${{ github.event.release.tag_name }}.zip" # Package asset files into .zip

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: "yFGB1mRk"
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          files: |-
            Fireworks-DP_v${{ github.event.release.tag_name }}.zip
            Fireworks-RP_v${{ github.event.release.tag_name }}.zip
          primary-file: Fireworks-DP_v${{ github.event.release.tag_name }}.zip
          file-types: Fireworks-RP_v${{ github.event.release.tag_name }}.zip=optional-resource-pack
          loaders: "datapack"
          game-versions: |-
            26.2-rc-2
          channel: "release"
